services:
  thera-app-db:
    volumes:
      - mysql:/var/lib/mysql
    container_name: thera-app-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      net:

  thera-ws-proxy:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: thera-ws-proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        PORT: 8080
        TIMEZONE: ${TIMEZONE}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - thera-app-backend
      - thera-app-frontend
    networks:
      net:

  thera-app-backend:
    volumes:
      - ./api:/app
    container_name: thera-app-backend
    build:
      context: .
      dockerfile: ./docker/nest/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "thera-app-db"
    networks:
      net:

  thera-app-frontend:
    volumes:
      - ./frontend:/app
    container_name: thera-app-frontend
    build:
      context: .
      dockerfile: ./docker/next/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "thera-app-backend"
    networks:
      net:

networks:
  net:
    name: thera-app-network
    external: false

volumes:
  mysql:
    name: thera-mysql-data