services:
  thera-app-db:
    volumes:
      - mysql:/var/lib/mysql
    container_name: thera-app-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      net:

  thera-app-node-cli:
    volumes:
      - ./backend:/api
      - ./frontend:/app
    container_name: thera-app-node-cli
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "thera-app-db"
    networks:
      net:

  thera-app-backend:
    volumes:
      - ./backend:/api
    container_name: thera-app-backend
    build:
      context: .
      dockerfile: ./docker/nestjs/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
        DB_NAME: ${DB_NAME}
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_HOST: thera-app-db
        DB_USER: root
    depends_on:
      - "thera-app-node-cli"
    networks:
      net:

  thera-app-frontend:
    volumes:
      - ./frontend:/app
    container_name: thera-app-frontend
    build:
      context: .
      dockerfile: ./docker/nextjs/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
        NEXT_PUBLIC_API_URL: http://localhost:${BACKEND_PORT:-8080}/api
    depends_on:
      - "thera-app-backend"
    networks:
      net:

  thera-app-ws-proxy:
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: thera-app-ws-proxy
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - thera-app-backend
      - thera-app-frontend
    networks:
      net:

networks:
  net:
    name: thera-app-network
    external: false

volumes:
  mysql:
    name: thera-app-mysql-data